version: 2.1
setup: true
orbs:
  orb-tools: circleci/orb-tools@12.0
  shellcheck: circleci/shellcheck@3.1
  node: circleci/node@5.2.0

filters: &filters
  tags:
    only: /.*/

workflows:
  lint-pack:
    jobs:
      - orb-tools/lint:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/review:
          exclude: RC002,RC005,RC009
          filters: *filters
      - shellcheck/check:
          filters: *filters
      - orb-tools/continue:
          pipeline_number: << pipeline.number >>
          vcs_type: << pipeline.project.type >>
          orb_name: react-native
          requires: [orb-tools/lint, orb-tools/pack, orb-tools/review, shellcheck/check]
          filters: *filters

  release:
    jobs:
      - node/run:
          yarn-run: semantic-release
          version: "20.11"
          pkg-manager: yarn
          filters:
            branches:
              only: master
